### PR TITLE
Location of signature algorithm in CSR

### LINKED ISSUE #167: Location of signature algorithm in C509CertificateRequest
In the newest document (https://github.com/cose-wg/CBOR-certificates/blob/master/draft-ietf-cose-cbor-encoded-cert.md), the location of signature algorithm in C509Certificate has been changed as discussed in https://github.com/cose-wg/CBOR-certificates/issues/149).

@authors: What about the same change to C509CertificateRequest?

### PR DESCRIPTION
**Pull request by gselander**
Missed this in #149. Fixes #167.

### CODE REVIEW

**Comment by emanjon** [comment]
I miss any discussion on this

**Comment by emanjon** [comment]
> This is alignment with location of signature algorithm in certificate. As noted in https://github.com/cose-wg/CBOR-certificates/issues/149, the same argument will apply to the location of the signature algorithm in a CRL. It seems reasonable to be consequent and do so also for the CSR.

One of the agreement was that we should keep the same location as in X.509. This PR breaks that. You could equally well say that based on previous discussions in is reasonable to not change...

**Comment by highlunder** [comment]
@gselander to mail and ask/discuss on the COSE list!

**Comment by gselander** [comment]
Email sent to the COSE list

**Pull request merged**
