### PR TITLE
New IANA section for Media Type application/cose-c509

### PR DESCRIPTION
**Pull request by highlunder**
Copy-paste-update from the application/cose-x509 in 9360. Not sure if we need to keep all N/A fields

### CODE REVIEW

**Comment by gselander** [comment]
Please change "draft-ietf-cose-cbor-encoded-cert" to "[[this document]]" (2 occurances) indicating to the RFC editor that they should replace it with the name of the published document.

**Comment by emanjon** [comment]
> Please change "draft-ietf-cose-cbor-encoded-cert" to "[[this document]]" (2 occurances) indicating to the RFC editor that they should replace it with the name of the published document.

Resolved

**Comment by emanjon** [comment]
I changed

OLD: the data is a CBOR sequence of single-entry COSE_C509 structures (encoding "bstr")
NEW: the data is a CBOR sequence of single-entry COSE_C509 structures (encoding "C509Certificate")

**Review by emanjon — APPROVED** [review]

**Comment by emanjon** [comment]
Lets discuss

the data is a CBOR sequence of single-entry COSE_C509 structures (encoding "C509Certificate")

This aligns with X509. But would it not be simpler with

the data is a single COSE_C509 structure

**Comment by highlunder** [comment]
> Lets discuss
> 
> the data is a CBOR sequence of single-entry COSE_C509 structures (encoding "C509Certificate")
> 
> This aligns with X509. But would it not be simpler with
> 
> the data is a single COSE_C509 structure

Do you mean to have a single COSE_C509 structure for the non-chain case? And only use sequences for chains?

**Comment by emanjon** [comment]
`COSE_C509 = C509Certificate / [ 2* C509Certificate ]`

My understanding of the current text is that you send a sequence of C509Certificate.

Makes more sense to me to send COSE_C509 for both single and chain.

Don't know why the COSE_X509 structure is not used in the COSE X509 RFC.

**Comment by emanjon** [comment]
#107 and #108 needs to align. Currently they are not

**Pull request merged**
